name: Nordic Pucks
author: Nordic Semiconductor
markdown: kramdown
highlighter: pygments
description: An mbed project
baseurl: /puck
github: http://www.github.com/NordicSemiconductor
# t twitter: http://www.twitter.com/
email: stian.jensen@nordicsemi.no
disqus: nordicpucks

collections:
  tutorials:
    output: true
  
